name: drop_box_uploader
description: upload | backup file to drop-box
version: 1.0.0

homepage: https://donnc.github.io/

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  dart_appwrite: ^1.0.1
  http: ^0.13.3
  logger: ^1.1.0
  path: ^1.8.0

dev_dependencies:
  lints: ^1.0.0
